stateDiagram

PreLoginIdle: Pre-login, Idle
Username: Username Entered
Password: Username and Password Entered
AwaitVerify: Awaiting Credential Verification From Server
Idle: Logged-in, Idle
AwaitAddBid: Awaiting Bid Verification From Server

[*] --> PreLoginIdle: Program starts
PreLoginIdle --> Username: Username text field is populated / Password text field is enabled
Username --> Password: Password text field is populated / Enable submit button
Password --> AwaitVerify: Submit button pressed / Sends info to CommController for server
AwaitVerify --> PreLoginIdle: Credentials were invalid / Signal LoginForm to reset 
AwaitVerify --> Idle: Credentials were valid / Signal LoginForm to close, signal MainForm to open
Idle --> AwaitAddBid: New valid bid placed / Send info to CommController for server
AwaitAddBid --> Idle: Server rejects bid / Signal MainForm to reset user input
Idle --> Idle: New info received from server / Product list refreshed
AwaitAddBid --> Idle: Server accepts bid and delivers updated products list / Product list refreshed

PreLoginIdle --> [*]: Program exited
Username --> [*]: Program exited
Password --> [*]: Program exited
Idle --> [*]: Program exited
AwaitAddBid --> [*]: Program exited
AwaitVerify --> [*]: Program exited
