stateDiagram

SendMsg: Sending Message
ReceiveMsg: Data Received

[*] --> Idle: Program starts
Idle --> SendMsg: Received message from MainControler
SendMsg --> Idle: Message sent to server
Idle --> ReceiveMsg: Received message from server
ReceiveMsg --> Idle: Message sent to MainController
Idle --> [*]: Program exits
