sequenceDiagram

actor User
participant MainForm
participant ProductsProxy
participant MainController
participant Decoder
participant CommController
participant WebSocket
participant user_controller
participant admin_controller
participant view

User ->> MainForm: PlaceBidClick(object sender, EventArgs e)
MainForm ->> MainController: HandleState(State state, string[] args)
MainController ->> MainController: ParseArguments(string[] args)
MainController ->> Decoder: Encode(Message msg)
MainController ->> CommController: SendMessage(string json)
CommController ->> WebSocket: Send(String json)
WebSocket ->> user_controller: read.for_each()
user_controller ->> admin_controller: to_admin_controller.send(UserCtrlrMsg msg)
admin_controller->> view: to_view.send(AdminCtrlrMsgView msg)
uer_controller ->> WebSocket: write.send(string json)
WebSocket ->> CommController: OnMessage(object Sender, MessageEventArgs e)
CommController ->> MainController: HandleState(State state, string[] args)
MainController ->> Decoder: DecodeJson(string json)
MainController ->> MainController: HandleMessage(Message msg)
MainController ->> ProductsProxy: InsertBid(int id, Bid bid, int quantity)
MainController ->> MainForm: DisplayState(State state, string arg)
