---
title: Use Case Title
---
flowchart LR
    A[Actor] --> |Event/Action| B
    B(Use Case Name) --> C
    C@{shape: comment, label: "1.One or several bullets describing the inputs
        2.One or two bullets with a short description of what the system will do with the inputs
        3.One or several bullets describing the outputs
    "}
    style C text-align:left
    style C shape:comment

